#!/bin/bash

echo ""
echo "========================================"
echo "Infrastructure Assessment Platform"
echo "========================================"
echo ""
echo "Backend Setup Instructions:"
echo "1. Navigate to backend folder: cd backend"
echo "2. Create virtual environment: python -m venv venv"
echo "3. Activate virtual environment: source venv/bin/activate"
echo "4. Install dependencies: pip install -r requirements.txt"
echo "5. Run backend: python run.py"
echo ""
echo "Backend will run on: http://localhost:5000"
echo ""
echo "Frontend Setup Instructions:"
echo "1. Navigate to frontend folder: cd frontend"
echo "2. Install dependencies: npm install"
echo "3. Start frontend: npm start"
echo ""
echo "Frontend will run on: http://localhost:3000"
echo ""
echo "========================================"
echo "Make sure both backend and frontend are running!"
echo "========================================"
echo ""
